### PR TITLE
Modernize meta.Ops, adapt it to new useful shapes, and use it more.

### LINKED ISSUE #1542: [8.0.x] Semigroup: broken macro (?)
Alright, so I was trying to write an example for `Semigroup` and I am getting a little frustrated here :D (mostly because I know nothing about macros)

I implemented a simple semigroup for String
```scala
implicit val StringSemigroup = new Semigroup[String] {
  def append(a1: String, a2: => String) = a1 + a2
}
```

Then I grab the usual suspects

```scala
import scalaz.typeclass.Semigroup
import scalaz.typeclass.Semigroup._
```

The second import gives me access to this:

```scala
object SemigroupSyntax {
  class OpsA[A: Semigroup](@silent a: A) {
    def append(f: => A): A = macro meta.Ops._f1[A, A]
  }
}
```

Now watch what happens when I try to append two strings:

```scala
@ "a".append("b") 
cmd11.sc:1: not enough arguments for method append: (a1: String, a2: => String)String.
Unspecified value parameter a2.
val res11 = "a".append("b")
                      ^
Compilation Failed
```

This should work, no? But for the heck of it, let's entertain the second parameter:

```scala
@ "a".append("b", "c") 
cmd11.sc:1: too many arguments (2) for macro method append: (f: => String)String
val res11 = "a".append("b", "c")
                            ^
Compilation Failed
```

So, one parameter is not enough, two is too many?
What's happening here? :D

### PR DESCRIPTION
**Pull request by hrhino**
Since 8.0.x won't support scala 2.10, there's no reason to bother using raw trees and `c.Expr`s all over the place. With this, it's possible to drop all the type parameters and write the impls in a somewhat less esoteric style (for when more shapes are inevitably needed).

The ops macros need to be blackbox, otherwise `f_0` won't fix the result type based on its type argument, and infer `Nothing`. It's not trivial to return a properly-typed tree if the return type is an arbitrary function of a cloud of types floating over the macro application, so it's easier to just accept the blackboxity and go ahead with unrestricted type inference.

Fixes #1542, so a ping to @NeQuissimus.

### CODE REVIEW

**Comment by TomasMikula** [comment]
Looks great! 👍

File: meta/shared/src/main/scala/scalaz/meta/Ops.scala [hunk 1]
```diff
@@ -1,35 +1,66 @@
...
+  /* def method(f: A)(g: B): R */
+  def fa_1_1(f: Tree)(g: Tree): Tree = q"$ev.$name($lhs, $f)($g)"
+
+  /* def method(f: A, g: B): R */
+  def f_2(f: Tree, g: Tree): Tree = q"$ev.$name($lhs)($f, $g)"
+
+  /** Destructured macro application.
+    * - `ev`: the typeclass evidence
+    * - `name`: the name of the invoked method
+    * - `targs`: the inferred type arguments of the method call
```
Comment (hrhino) [inline meta/shared/src/main/scala/scalaz/meta/Ops.scala]: Yikes, missed this last night. Will remove.

**Comment by NeQuissimus** [comment]
YES!

**Comment by jdegoes** [comment]
@hrhino Nice! Ready to merge whenever you are. Thanks!
